global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: connector
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - connector:8085
rule_files:
  - rules.yml
