groups:
  - name: example
    rules:
      - record: job:http_requests:rate5m
        expr: sum without(instance,uri, method, status) (rate(http_server_requests_seconds_count[5m]))
      - record: job:http_requests:rate5m:avg_over_time_1w
        expr: avg_over_time(job:http_requests:rate5m[1w])
      - record: job:http_requests:rate5m:stddev_over_time_1w
        expr: stddev_over_time(job:http_requests:rate5m[1w])
